- name: Install node and npm
  hosts: all   
  tasks:  
  - name: Update yum repo and cache
    yum: update_cache=True
  - name: Install nodejs and npm
    yum: 
      pkg:
        - nodejs
        - npm

- name : Create a new linux user for node app
  hosts: all
  vars_files:
    - variables
  tasks:
  - name: create a new user
    user:
      name: "{{linux_user}}"
      comment: Node user
    register: user_creation_result
  - debug: msg={{user_creation_result}}


- name: Deploy nodejs app
  hosts: all
  become: True
  become_user: "{{linux_user}}"
  vars_files:
    - variables
  tasks:
    - name: Unpack the nodejs tar file
      unarchive: 
        src: "{{source_location}}/nodejs-app-{{version}}.tgz"
        dest: "{{user_home_dir}}"

    - name: Install dependencies
      npm:
        path: "{{user_home_dir}}/package"

    - name: Start the application
      command: 
        chdir: "{{user_home_dir}}/package/app"
        cmd: node server
      async: 1000
      poll: 0

    - name: Ensure the app
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
